project:
  type: website

website:
  title: "IS415 Geospatial-KMR"
  navbar:
    left:
      - text: "Hands-on Exercise"
        menu:
          - href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html"
            text: "Hands-on Exercise 1"
          
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: sandstone
    css: styles.css
    toc: true

editor: visual

