---
title: "In-class Exercise 5"
author: "Kwek Ming Rong"
date: "06 Februrary 2023"
date-modified: "`r Sys.Date()`"
format: html
execute:
  eval: true
  echo: true
  warning: false
editor: visual
---

# 1. Getting Started 

```{r}
pacman::p_load(tidyverse, tmap, sf, sfdep)
```

## 1.1 Importing Data

Importing data shapefile for study area
```{r}
studyArea <- st_read(dsn = "Data/Geospatial", 
                layer = "study_area") %>%
  st_transform(crs = 3829)
```

Importing data shapefile for stores
```{r}
stores <- st_read(dsn = "Data/Geospatial", 
                layer = "stores") %>%
  st_transform(crs = 3829)
```

## 1.2 Visualising the SF layer

```{r}
tmap_mode("view")
tm_shape(studyArea) +
  tm_polygons() +
  tm_shape(stores) +
  tm_dots(col = "Name", 
          size = 0.01,
          border.col = "black",
          border.lwd = 0.5) +
  tm_view(set.zoom.limits = c(12, 16))
```

## 1.3 Local Colocation Quotients (LCLQ)

```{r}
nb <- include_self(
  st_knn(st_geometry(stores), 6))
```

```{r}
wt <- st_kernel_weights(nb,
                        stores, 
                        "gaussian",
                        adaptive = TRUE)
```

```{r}
FamilyMart <- stores %>%
  filter(Name == "Family Mart")
A <- FamilyMart$Name
```

```{r}
SevenEleven <- stores %>%
  filter(Name == "7-Eleven")
B <- SevenEleven$Name
```

```{r}
LCLQ <- local_colocation(A, B, nb, wt , 49)
```

```{r}
LCLQ_stores <- cbind(stores, LCLQ)
```

```{r}
tmap_mode("view")
tm_shape(studyArea) +
  tm_polygons() +
  tm_shape(LCLQ_stores) +
  tm_dots(col = "Name", 
          size = 0.01,
          border.col = "black",
          border.lwd = 0.5) +
  tm_view(set.zoom.limits = c(12, 16))
```